import { FilterKeys, PlayId } from "@/constants";

export const DUMMY_CREATORS: { id: number; role: FilterKeys; name: string }[] =
    [
        { id: 1, role: 0, name: "칼레이도스코프 창작자 1" },
        { id: 2, role: 0, name: "칼레이도스코프 창작자 2" },
        { id: 3, role: 0, name: "칼레이도스코프 창작자 3" },
        { id: 4, role: 0, name: "칼레이도스코프 창작자 4" },
        { id: 5, role: 0, name: "칼레이도스코프 창작자 5" },
        { id: 6, role: 0, name: "칼레이도스코프 창작자 6" },
        { id: 7, role: 0, name: "칼레이도스코프 창작자 7" },
        { id: 8, role: 0, name: "칼레이도스코프 창작자 8" },
        { id: 9, role: 0, name: "칼레이도스코프 창작자 9" },
        { id: 10, role: 0, name: "칼레이도스코프 창작자 10" },
        { id: 11, role: 1, name: "A.I? 창작자 1" },
        { id: 12, role: 1, name: "A.I? 창작자 2" },
        { id: 13, role: 1, name: "A.I? 창작자 3" },
        { id: 14, role: 1, name: "A.I? 창작자 4" },
        { id: 15, role: 1, name: "A.I? 창작자 5" },
        { id: 16, role: 1, name: "A.I? 창작자 6" },
        { id: 17, role: 1, name: "A.I? 창작자 7" },
        { id: 18, role: 1, name: "A.I? 창작자 8" },
        { id: 19, role: 1, name: "A.I? 창작자 9" },
        { id: 20, role: 1, name: "A.I? 창작자 10" },
        { id: 21, role: 2, name: "오브젝트! 창작자 1" },
        { id: 22, role: 2, name: "오브젝트! 창작자 2" },
        { id: 23, role: 2, name: "오브젝트! 창작자 3" },
        { id: 24, role: 2, name: "오브젝트! 창작자 4" },
        { id: 25, role: 2, name: "오브젝트! 창작자 5" },
        { id: 26, role: 2, name: "오브젝트! 창작자 6" },
        { id: 27, role: 2, name: "오브젝트! 창작자 7" },
        { id: 28, role: 2, name: "오브젝트! 창작자 8" },
        { id: 29, role: 2, name: "오브젝트! 창작자 9" },
        { id: 30, role: 2, name: "오브젝트! 창작자 10" },
        { id: 31, role: "staff", name: "기획팀 1" },
        { id: 32, role: "staff", name: "기획팀 2" },
        { id: 33, role: "staff", name: "기획팀 3" },
        { id: 34, role: "staff", name: "기획팀 4" },
        { id: 35, role: "staff", name: "기획팀 5" },
        { id: 36, role: "staff", name: "기획팀 6" },
        { id: 37, role: "staff", name: "기획팀 7" },
        { id: 38, role: "staff", name: "기획팀 8" },
        { id: 39, role: "staff", name: "기획팀 9" },
        { id: 40, role: "staff", name: "기획팀 10" },
    ];

export const DUMMY_QUESTIONS = (playId: PlayId) => [
    {
        id: 0,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: true,
    },
    {
        id: 1,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: false,
    },
    {
        id: 2,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: true,
    },
    {
        id: 3,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: false,
    },
    {
        id: 4,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: true,
    },
    {
        id: 5,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: false,
    },
    {
        id: 10,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: true,
    },
    {
        id: 11,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: false,
    },
    {
        id: 12,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: true,
    },
    {
        id: 13,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: false,
    },
    {
        id: 14,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: true,
    },
    {
        id: 15,
        playId,
        text: "sdoifhp;ahrueah;va;rbv;fhg;jg;ajeogieaj;gaoehg;aheg;rhgr;gh;auhg;gaergh;reag",
        isAnswered: false,
    },
];
